### ISSUE TITLE
Site seems to incorrectly decode Unicode characters in names during signup.

### ISSUE THREAD

**Issue by stebet** [dotnet-foundation/membership#10]
I clicked the "Activate Membership" link in the email I received, and after signing in with my Microsoft Account, the membership page showed up like this.

![image](https://user-images.githubusercontent.com/661658/54018693-470afd80-4181-11e9-9f4a-3faaad7ef5d3.png)

**Comment by jongalloway** [comment]
Thanks for reporting, and sorry about that. Your name is perfect for checking our Unicode issues. :)

The error was actually in the invitation process that added you to our Azure AD. I've fixed your name there, fixed the invitation process, and verified using a test account, so I think this should be set now. Can you verify by looking at your account again?

![chrome_2019-03-08_11-44-56](https://user-images.githubusercontent.com/68539/54051937-dfac7800-4197-11e9-96ba-19c92c9193f4.png)

**Comment by jongalloway** [comment]
Fixed by https://github.com/dotnet-foundation/membership/commit/a4055f0dc4662c70a587287c6b252b912e81452f#diff-b7a0b5819c7b6957704761163c137db7R60
