### ISSUE TITLE
Unable to log in: Selected user account does not exist in tenan

### ISSUE THREAD

**Issue by samrueby** [dotnet-foundation/membership#15]
When I attempt to log in, I see this message:

> Selected user account does not exist in tenant '.NET Foundation' and cannot access the application 'a913d131-bc7d-49ff-b286-3e1ad46ddc57' in that tenant. The account needs to be added as an external user in the tenant first. Please use a different account.

However, I've logged in before. I've even already paid my dues. But I'm unable to get in now.

**Comment by onovotny** [comment]
Have you tried an in-private /incogneto session?  Could you be signed into Google using another account that's interfering with single sign on?

**Comment by samrueby** [comment]
Yeah, I've tried incognito: same result.

**Comment by onovotny** [comment]
Are you able to record a fiddler trace (with https interception enabled)? There's not a lot to go on here; this part is handled by Azure AD federated to Google. After entering your email address, are you getting redirected to Google for sign in?

**Comment by samrueby** [comment]
I can do that. Wouldn't want to attach it public there:  where would I send?

**Comment by onovotny** [comment]
if you can send it to jon at dotnetfoundation.org, we can look into it.

**Comment by samrueby** [comment]
I am not being redirected to Google. I sign in with my Microsoft account.

**Comment by onovotny** [comment]
That's the problem -- this account appears to be federating with Google, not Microsoft.

**Comment by onovotny** [comment]
Couple questions -- did you have a Microsoft Account with that gmail address before this? When you clicked the accept invite button, did it take you to Google (do you recall?)

**Comment by samrueby** [comment]
You're right: it is associated with my Google account. I didn't realize that just because I used my gmail address. I hope I'm not missing out on something by not using my Microsoft account's address. 

Yes I did used to have a Microsoft account with that gmail account: but I haven't used it in years. It must have taken to me to Google when I accepted the invite.

**Comment by onovotny** [comment]
There's no difference in signing in between MSA and Google other than minimzing an extra hop.

So when you enter your email, it's still taking you to MSA and not Google? If so, I'll raise an issue with the AAD B2B team.

**Comment by samrueby** [comment]
It takes me to MSA but I just clicked "use another account" and entering my gmail in there correctly takes me to gmail.

**Comment by onovotny** [comment]
Any chance you can take a video recording of you doing that? That sounds clunky and I'd like to see if the B2B team can do something to improve that.

**Comment by samrueby** [comment]
Sure.

**Comment by samrueby** [comment]
Emailed.

**Comment by CERN-CH** [comment]
<[%@%"Hey Google" mapping software and Hardware ÅUTO_CÅD_(³D)_(²D)%@%]> for thread patterns of clothing to match CPU switching on and off with hot and cold wire threads switching wire expansion hot wire expansion switch off mapping software and Hardware wire switching thread pattern expansion for cooling on mapping software and Hardware repeating thread processing mapping software and Hardware expansion of periodic tables metals same process of cotton threads to wire threads of central processing units of CPU switching mapping software and Hardware thread weaving in and out mapping software and Hardware points of access of switching on and off mapping software and Hardware wire expansion threading mapping software and hardware for contact points mapping software and Hardware for expansion of wire mapping software and Hardware for expansion of wire when it gets hot mapping software and Hardware DETECTING TEMPERATURES PERIODIC TABLE ELECTRONS SWITCHING switching off mapping software and Hardware cooling of the Dexpansion of wire`s mapping software and Hardware switching on  Dexpansion`s No accumulating`s🌡️ liquid`s accumulating hydrogen`s accumulation`s —²5⁶°©️=%@%(%@%PSI%@%»°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°÷°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°:°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°÷°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°\°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°÷°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°%°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°÷°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°\°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°÷°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°™️°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°÷°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°®️°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°÷°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°:°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°÷°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°\°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°÷°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°%°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°÷°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°\°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°÷°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°©️°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°÷°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°:°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°÷°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°\°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°÷°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°%°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°÷°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°\°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°÷°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°®️°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°÷°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°:°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°÷°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°\°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°÷°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°%°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°÷°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°\°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°÷°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°™️°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°÷°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°:°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°÷°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°\°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°÷°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°%°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°÷°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°\°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°÷°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°—°`°~°`°_°`°~°`°³∅`∅∅∅.0.00100.0.0⁰1⁰0.0.00100.⁰0¹0⁰.00100.⁰.0⁰1⁰0. 0.00100.0%@%)%@%DECELERATING`S DECELERATING`S ACCELERATING`S DECELERATING`S accumulating`s🌡️ accumulations liquid`s dexpansion`s%@%]>

**Comment by CERN-CH** [comment]
<[PNG]>SOUND PHONE SYMBOLPHONE NUMBER_00100<[PNG/]>
