### ISSUE TITLE
Add information about ending membership

### ISSUE THREAD

**Issue by jeroenheijmans** [dotnet-foundation/membership#168]
Neither [the FAQ](https://dotnetfoundation.org/about/faq) nor [the "Become a Member"](https://dotnetfoundation.org/member/become-a-member) nor [the "Membership Policy"](https://dotnetfoundation.org/about/member-policy) page has any information on how to end your membership.

How can one end their membership, and can that information be made clear(er) on the website?

**Comment by jeroenheijmans** [comment]
For those who land here from a web search, I ended up using [the contact information](https://github.com/dotnet-foundation/Home#feedback-or-other-questions) and tried to do it via e-mail. If you need to send a similar e-mail, here's a template:

```
Dear .NET Foundation,

Would you be so kind to end my membership? My registered e-mail address
is **<your email here>**

I had tried to find a form or something to do this but couldn't find any,
see also: https://github.com/dotnet-foundation/membership/issues/168 

Thanks for your time, and good luck with the continued efforts!

Kind regards
```

Hope that helps someone!

**Comment by jeroenheijmans** [comment]
@nicoleabuhakmeh Thanks for that.

I had already stopped my yearly contribution. Just felt it was unfair to remain as a "member" when I was stopping my financial and time investment in the community. That's why I figured it'd make sense to be removed. If it's a big hassle to remove my account, you can leave me in there or mark my account "inactive".

For me personally, all is well like this.

I'd still recommend adding _something_ to the foundation's membership static website or its FAQ, others might be looking for similar information? (That was my _main_ reason for opening this GitHub issue.)

Cheers for your kind interaction, and of course all the best!

**Comment by nicoleabuhakmeh** [comment]
No worries or hassle at all.  Please reach back out if something changes. :)

**Comment by jeroenheijmans** [comment]
Heya! The issue got closed as "completed" I see, curious to know where the info got added? The three links posted in my original post (where I expected to see said info) don't at first sight seem to have relevant info about ending membership?

**Comment by nicoleabuhakmeh** [comment]
I took your information that you created and added to a document that we'll be using in the new membership portal about canceling membership.

**Comment by jeroenheijmans** [comment]
Cheers!
