### ISSUE TITLE
Every page makes a request for a /manifest.json (resulting in a 404)

### ISSUE THREAD

**Issue by NickCraver** [dotnet-foundation/membership#2]
This is due to:
```html
<link rel="manifest" href="/manifest.json">
```
in the header. Is this intended to be there, or should we just remove the ref?

**Comment by onovotny** [comment]
Thanks, fixed and it'll auto-deploy out as soon as it builds.

**Comment by jongalloway** [comment]
Added manifest.json and reference back in https://github.com/dotnet-foundation/membership/commit/53520618d38e8283f012237d493f704c704fd539

This is supposed to allow supporting high dpi favicons, not sure how widely adopted it is. https://developer.mozilla.org/en-US/docs/Web/Manifest
