### ISSUE TITLE
Running the app locally throws exceptions

### ISSUE THREAD

**Issue by IrisClasson** [dotnet-foundation/membership#24]
Launching the app locally, by using Visual Studio or dotnet cli, throws during startup with AzureServiceTokenProviderException. I was unable yo bypass this by commenting out the startup code.

**Comment by onovotny** [comment]
We should have a way to get the app running, even if it doesn't support rendering all functionality.

**Comment by jongalloway** [comment]
From looking at the [KeyVault docs](https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-2.2), it looks like we could explicitly load the settings using the KeyVault Configuration Provider. That would allow us to have defaults and switches in appsettings.json for local dev, and could also set an environment prefix.

**Comment by jongalloway** [comment]
Fixed by 4a7b4de2aebec7effdd7bdfb1e0280ea34f68b62

Adds "Local Development" launch profile that skips authentication. We could enhance this in the future to sub in another auth provider for local dev, but this at least allows for content updates without KeyVault config.
