### ISSUE TITLE
How to become a member of .NET Foundation on GitHub?

### ISSUE THREAD

**Issue by Marusyk** [dotnet-foundation/membership#31]
I have a stupid question: How to become a member of .NET Foundation on GitHub? 
I'm Foundation Member and want to know how to get  .NET Foundation badge im my GitHub profile?

Thank you in advance

**Comment by Potapy4** [comment]
Have you entered your GitHub URL on the .NET membership website? I think you should automatically receive an invitation.

/cc @jongalloway

**Comment by Marusyk** [comment]
Yes, I have

**Comment by Gnbrkm41** [comment]
I always thought it's something that only MS employees get access to... but if it is not the case, I have not received an invitation.

**Comment by Marusyk** [comment]
any news?

**Comment by Marusyk** [comment]
yep, now I got invitation. thanks all
