### ISSUE TITLE
Graph Beta MyGet Feed No Longer Exists

### ISSUE THREAD

**Issue by goh-chunlin** [dotnet-foundation/membership#32]
When I did `dotnet restore`, there is an error message saying "Unable to load the service index for source https://www.myget.org/F/graphbeta/api/v3/index.json", as shown in the following screenshot.

![image](https://user-images.githubusercontent.com/8535306/66126909-1b6bcb00-e61d-11e9-866e-f18275976b85.png)

**Comment by onovotny** [comment]
I've removed it from the nuget.config as it shouldn't be required anymore.

**Comment by goh-chunlin** [comment]
Thank you, @onovotny =)
