### ISSUE TITLE
Localhost Authorization Issue

### ISSUE THREAD

**Issue by goh-chunlin** [dotnet-foundation/membership#36]
I have no problem on getting the Membership website up and running. However, I saw the following message when I am accessing the Profile page.

```
14:08:49 [Debug] () The request path "/Profile" does not match a supported file type

14:08:49 [Debug] () 1 candidate(s) found for the request path '"/Profile"'

14:08:49 [Debug] () Endpoint '"Membership.Controllers.ProfileController.Index (Membership)"' with route pattern '"{controller=Home}/{action=Index}/{id?}"' is valid for the request path '"/Profile"'

14:08:49 [Debug] () Request matched endpoint '"Membership.Controllers.ProfileController.Index (Membership)"'

14:08:49 [Information] () "AzureADCookie" was not authenticated. Failure message: "No principal."

```

Please share with us on how to fix this so that we can document it down on README.

Thank you!

**Comment by onovotny** [comment]
We don't currently support debugging this application locally as it requires secrets used in production. 

We'd be happy to take a PR that improves the experience with dummy data/disables certain bits when the secrets aren't available for local dev.
